FROM debian:13-slim@sha256:a29215f6a35e51e22adffa17f89e9d2ef06214e64a2bad10d765c46aea49f11f
RUN apt-get update && apt-get install -y --no-install-recommends qemu-system-x86 qemu-utils ovmf genisoimage python3 ca-certificates curl && rm -rf /var/lib/apt/lists/*
WORKDIR /work
